require("script_client.OpenUI")
require "script_client.languagePlayer"
-- World.Timer(10, function()
--     --local guiMgr = GUIManager:Instance()
-- 	--local window = UI:openWindow("")
-- end)
PackageHandlers.sendClientHandler("getValuePlayer", nil, function (player)
    print("eeeeeeeeesssssssssssss")
    print(Lib.pv(player))
    UI:openWindow("main",nil,nil,player)
end)
